name: Test

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run unit/functional tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: nightly
        env:
          PKGLS_LOG: debug
          RUST_BACKTRACE: 1

  coverage:
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests and generate code coverage
        run: cargo +nightly tarpaulin --all-features --workspace --tests --timeout 120 --fail-under 0
        env:
          PKGLS_LOG: debug
          RUST_BACKTRACE: 1
